apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: prometheus-example-monitor
  name: prometheus-example-podmonitor
  namespace: ns1
spec:
  namespaceSelector: {}
  selector:
    matchLabels:
      app: prometheus-example-app
  podMetricsEndpoints:
  - port: web
    interval: 2s
